version: '3.8'
services:
  guacamole:
    image: guacamole/guacamole
    ports:
    - 8080:8080
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
    depends_on:
    - guacd
  guacd:
    image: guacamole/guacd
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: guacamole_password
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
